export const formColumns = [
    [
        {title: '监区',dataIndex: 'area',},
        {title: '加扣分',dataIndex: 'score',},
        {title: '特殊事件',dataIndex: 'special',},
        {title: '超产分',dataIndex: 'work',},
        {title: '月奖',dataIndex: 'reward',},
        {title: '互监组',dataIndex: 'group',},
        {title: '录入时间',dataIndex: 'logDate',},
    ],
    [
        {title: 'ID',dataIndex: 'id',auth:'super',},
        {title: '日期',dataIndex: 'date',},
        {title: '监区',dataIndex: 'area',},
        {title: '超欠产人数',dataIndex: 'count',},
        {title: '合计分数',dataIndex: 'sum',},
        {title: '详情',dataIndex: 'details',},
    ],
    [
        {title: 'ID',dataIndex: 'id',auth:'super',},
        {title: '日期',dataIndex: 'date',},
        {title: '监区',dataIndex: 'area',},
        {title: '互监组个数',dataIndex: 'count',},
        {title: '人数',dataIndex: 'sum',},
        {title: '详情',dataIndex: 'details',},
    ],
    [
        {title: 'ID',dataIndex: 'id',auth:'super',},
        {title: '日期',dataIndex: 'date',},
        {title: '监区',dataIndex: 'area',},
        {title: '月奖人数',dataIndex: 'count',},
        {title: '合计分数',dataIndex: 'sum',},
        {title: '详情',dataIndex: 'details',},
    ],
    [
        {title: 'ID',dataIndex: 'id',width:'auto',auth:'super',},
        {title: '监区',dataIndex: 'area',width:'auto',},
        {title: '日期',dataIndex: 'date',width:100,},
        {title: '编号',dataIndex: 'num',width:'auto',},
        {title: '姓名',dataIndex: 'name',width:'auto',},
        {title: '类别',dataIndex: 'part',width:'auto',},
        {title: '事由',dataIndex: 'reason',width:'auto',},
        {title: '条款',dataIndex: 'clause',width:'auto',},
        {title: '分值',dataIndex: 'score',width:'auto',},
        {title: '处理民警',dataIndex: 'police',width:'auto',},
        {title: '审核',dataIndex: 'police1',width:'auto',},
        {title: '审批',dataIndex: 'police2',width:'auto',},
        {title: '录入时间',dataIndex: 'logDate',width:'auto',},
    ],
    [
        {title: 'ID',dataIndex: 'id',width:'auto',auth:'super',},
        {title: '监区',dataIndex: 'area',width:'auto',},
        {title: '编号',dataIndex: 'num',width:'auto',},
        {title: '姓名',dataIndex: 'name',width:'auto',},
        {title: '特殊事件',dataIndex: 'reason',width:'auto',},
        {title: '起',dataIndex: 'start',width:'auto',},
        {title: '止',dataIndex: 'finish',width:'auto',},
        {title: '处理民警',dataIndex: 'police',width:'auto',},
        {title: '审核',dataIndex: 'police1',width:'auto',},
        {title: '审批',dataIndex: 'police2',width:'auto',},
        {title: '录入时间',dataIndex: 'logDate',width:'auto',},
    ],
    [
        {title: 'ID',dataIndex: 'id',width:'auto',auth:'super',},
        {title: '监区',dataIndex: 'area',width:'auto',},
        {title: '编号',dataIndex: 'num',width:'auto',},
        {title: '姓名',dataIndex: 'name',width:'auto',},
        {title: '互监组编号',dataIndex: 'group',width:'auto',},
        {title: '重点互监组',dataIndex: 'sort',width:'auto',},
        {title: '处理民警',dataIndex: 'police',width:'auto',},
        {title: '审核',dataIndex: 'police1',width:'auto',},
        {title: '录入时间',dataIndex: 'logDate',width:'auto',},
    ],
]

export const formLists = [
    [
        {title: '监区',dataIndex: 'area',},
        {title: '日期',dataIndex: 'date',},
        {title: '有劳动定额人数',dataIndex: 'num',},
        {title: '姓名',dataIndex: 'name',},
        {title: '加分事由',dataIndex: 'tips',},
        {title: '超欠产分',dataIndex: 'score',},
        {title:'录入时间',dateIndex:'logDate',}
    ],
]